language: node_js
node_js:
  - "10"

cache:
  directories:
  - node_modules

script:
  - yarn build-storybook
  - npm install -g now
  - yarn copy_now
  - cd storybook-static && now --no-clipboard --token=$NOW_TOKEN  && now alias --token=$NOW_TOKEN

